meta_title: "DENTACOOP"
meta_description: "Première coopérative dentaire française de vente de matériel et de services pensée et créée par des chirugiens-dentistes."
meta_image: "assets/logo.png" # Une image dans votre dossier app/assets/images/
# twitter_account: "@RevancheSites"
